"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    home: "Home",
    login: "Login/Signup",
    userDashboard: "User Dashboard",
    weaverDashboard: "Weaver Dashboard",
    about: "About",
    contact: "Contact",
    tagline: "Connecting Heritage with Hearts",

    // Common
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    loading: "Loading...",
    noResults: "No results found",

    // User Dashboard
    welcomeUser: "Welcome, Saree Lover!",
    discoverWeavers: "Discover and connect with talented women weavers across India",
    searchWeavers: "Search weavers by name, region, or specialty...",
    filterBy: "Filter By",
    pattern: "Pattern",
    material: "Material",
    region: "Region",
    allPatterns: "All Patterns",
    allMaterials: "All Materials",
    allRegions: "All Regions",
    clearFilters: "Clear Filters",
    weaversFound: "weavers found",
    yearsExperience: "years experience",
    specialties: "Specialties",
    recentWork: "Recent Work",
    languages: "Languages",
    priceRange: "Price Range",
    reviews: "reviews",
    verified: "Verified",
    available: "Available",
    busy: "Busy",
    connect: "Connect",
    viewProfile: "View Profile",
    contactWeaver: "Contact Weaver",

    // Weaver Dashboard
    welcomeWeaver: "Welcome, Master Weaver!",
    empowerCraft: "Empower your craft with AI tools and government support",
    budgetPlanner: "AI Budget Planner",
    estimateBudget: "Estimate Budget",
    machinesRequired: "Machines Required",
    numberOfLooms: "Number of looms",
    materialQuantity: "Material Quantity (kg)",
    yarnQuantity: "Yarn quantity",
    laborDays: "Labor Days",
    workingDays: "Working days",
    estimatedBudget: "Estimated Budget",
    govSchemes: "Government Schemes",
    learningResources: "Learning Resources",
    profileManager: "Profile Manager",
    uploadWork: "Upload Work Images",
    accessCourses: "Access courses, guides, and video tutorials to enhance your skills",
    uploadManage: "Upload your work and manage your specialties",

    // Government Schemes
    handloomScheme: "Handloom Weavers Comprehensive Welfare Scheme",
    handloomDesc: "Financial assistance and insurance coverage for handloom weavers",
    developmentScheme: "National Handloom Development Programme",
    developmentDesc: "Skill development and technology upgradation support",
    yarnScheme: "Yarn Supply Scheme",
    yarnDesc: "Subsidized yarn supply to handloom weavers",
    learnMore: "Learn More",

    // Resources
    traditionalTechniques: "Traditional Weaving Techniques",
    digitalMarketing: "Digital Marketing for Artisans",
    loomMaintenance: "Loom Maintenance & Care",
    course: "Course",
    pdfGuide: "PDF Guide",
    video: "Video",
    access: "Access",

    // Pagination
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",

    // Materials and Patterns (keep existing ones and add more)
    cotton: "Cotton",
    silk: "Silk",
    khadi: "Khadi",
    linen: "Linen",
    chiffon: "Chiffon",
    bandhani: "Bandhani",
    kanjivaram: "Kanjivaram",
    ikat: "Ikat",
    banarasi: "Banarasi",
    geometric: "Geometric",
    floral: "Floral",
    paisley: "Paisley",
    templeBorders: "Temple Borders",
    zariWork: "Zari Work",
    blockPrint: "Block Print",
    silkWeaving: "Silk Weaving",
    cottonSarees: "Cotton Sarees",
    bananasiSaree: "Banarasi Saree",
  },
  hi: {
    // Navigation
    home: "होम",
    login: "लॉगिन/साइनअप",
    userDashboard: "उपयोगकर्ता डैशबोर्ड",
    weaverDashboard: "बुनकर डैशबोर्ड",
    about: "हमारे बारे में",
    contact: "संपर्क",
    tagline: "विरासत को दिलों से जोड़ना",

    // Common
    search: "खोजें",
    filter: "फिल्टर",
    clear: "साफ़ करें",
    apply: "लागू करें",
    save: "सेव करें",
    cancel: "रद्द करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    view: "देखें",
    loading: "लोड हो रहा है...",
    noResults: "कोई परिणाम नहीं मिला",

    // User Dashboard
    welcomeUser: "स्वागत है, साड़ी प्रेमी!",
    discoverWeavers: "भारत भर की प्रतिभाशाली महिला बुनकरों को खोजें और जुड़ें",
    searchWeavers: "नाम, क्षेत्र या विशेषता से बुनकर खोजें...",
    filterBy: "फिल्टर करें",
    pattern: "पैटर्न",
    material: "सामग्री",
    region: "क्षेत्र",
    allPatterns: "सभी पैटर्न",
    allMaterials: "सभी सामग्री",
    allRegions: "सभी क्षेत्र",
    clearFilters: "फिल्टर साफ़ करें",
    weaversFound: "बुनकर मिले",
    yearsExperience: "साल का अनुभव",
    specialties: "विशेषताएं",
    recentWork: "हाल का काम",
    languages: "भाषाएं",
    priceRange: "मूल्य सीमा",
    reviews: "समीक्षाएं",
    verified: "सत्यापित",
    available: "उपलब्ध",
    busy: "व्यस्त",
    connect: "जुड़ें",
    viewProfile: "प्रोफाइल देखें",
    contactWeaver: "बुनकर से संपर्क करें",

    // Weaver Dashboard
    welcomeWeaver: "स्वागत है, मास्टर बुनकर!",
    empowerCraft: "AI उपकरण और सरकारी सहायता से अपने शिल्प को सशक्त बनाएं",
    budgetPlanner: "AI बजट प्लानर",
    estimateBudget: "बजट का अनुमान लगाएं",
    machinesRequired: "आवश्यक मशीनें",
    numberOfLooms: "करघों की संख्या",
    materialQuantity: "सामग्री की मात्रा (किलो)",
    yarnQuantity: "धागे की मात्रा",
    laborDays: "श्रम दिवस",
    workingDays: "कार्य दिवस",
    estimatedBudget: "अनुमानित बजट",
    govSchemes: "सरकारी योजनाएं",
    learningResources: "शिक्षण संसाधन",
    profileManager: "प्रोफाइल प्रबंधक",
    uploadWork: "कार्य चित्र अपलोड करें",
    accessCourses: "अपने कौशल को बढ़ाने के लिए पाठ्यक्रम, गाइड और वीडियो ट्यूटोरियल तक पहुंचें",
    uploadManage: "अपना काम अपलोड करें और अपनी विशेषताओं का प्रबंधन करें",

    // Government Schemes
    handloomScheme: "हथकरघा बुनकर व्यापक कल्याण योजना",
    handloomDesc: "हथकरघा बुनकरों के लिए वित्तीय सहायता और बीमा कवरेज",
    developmentScheme: "राष्ट्रीय हथकरघा विकास कार्यक्रम",
    developmentDesc: "कौशल विकास और प्रौद्योगिकी उन्नयन सहायता",
    yarnScheme: "धागा आपूर्ति योजना",
    yarnDesc: "हथकरघा बुनकरों को सब्सिडी युक्त धागा आपूर्ति",
    learnMore: "और जानें",

    // Resources
    traditionalTechniques: "पारंपरिक बुनाई तकनीक",
    digitalMarketing: "कारीगरों के लिए डिजिटल मार्केटिंग",
    loomMaintenance: "करघा रखरखाव और देखभाल",
    course: "पाठ्यक्रम",
    pdfGuide: "PDF गाइड",
    video: "वीडियो",
    access: "पहुंच",

    // Pagination
    previous: "पिछला",
    next: "अगला",
    page: "पृष्ठ",
    of: "का",

    // Materials and Patterns
    cotton: "कपास",
    silk: "रेशम",
    khadi: "खादी",
    linen: "लिनन",
    chiffon: "शिफॉन",
    bandhani: "बंधनी",
    kanjivaram: "कांजीवरम",
    ikat: "इकत",
    banarasi: "बनारसी",
    geometric: "ज्यामितीय",
    floral: "फूलों का",
    paisley: "पेस्ले",
    templeBorders: "मंदिर बॉर्डर",
    zariWork: "जरी का काम",
    blockPrint: "ब्लॉक प्रिंट",
    silkWeaving: "रेशम बुनाई",
    cottonSarees: "कपास साड़ी",
    bananasiSaree: "बनारसी साड़ी",
  },
  // Add similar comprehensive translations for other languages...
  bn: {
    // Navigation
    home: "হোম",
    login: "লগইন/সাইনআপ",
    userDashboard: "ব্যবহারকারী ড্যাশবোর্ড",
    weaverDashboard: "তাঁতি ড্যাশবোর্ড",
    about: "সম্পর্কে",
    contact: "যোগাযোগ",
    tagline: "ঐতিহ্যকে হৃদয়ের সাথে সংযুক্ত করা",

    // Common
    search: "অনুসন্ধান",
    filter: "ফিল্টার",
    clear: "পরিষ্কার",
    apply: "প্রয়োগ",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    view: "দেখুন",
    loading: "লোড হচ্ছে...",
    noResults: "কোন ফলাফল পাওয়া যায়নি",

    // User Dashboard
    welcomeUser: "স্বাগতম, শাড়ি প্রেমিক!",
    discoverWeavers: "ভারত জুড়ে প্রতিভাবান মহিলা তাঁতিদের আবিষ্কার করুন এবং সংযুক্ত হন",
    searchWeavers: "নাম, অঞ্চল বা বিশেষত্ব দিয়ে তাঁতি খুঁজুন...",
    filterBy: "ফিল্টার করুন",
    pattern: "প্যাটার্ন",
    material: "উপাদান",
    region: "অঞ্চল",
    allPatterns: "সব প্যাটার্ন",
    allMaterials: "সব উপাদান",
    allRegions: "সব অঞ্চল",
    clearFilters: "ফিল্টার পরিষ্কার করুন",
    weaversFound: "তাঁতি পাওয়া গেছে",
    yearsExperience: "বছরের অভিজ্ঞতা",
    specialties: "বিশেষত্ব",
    recentWork: "সাম্প্রতিক কাজ",
    languages: "ভাষা",
    priceRange: "মূল্য পরিসীমা",
    reviews: "পর্যালোচনা",
    verified: "যাচাইকৃত",
    available: "উপলব্ধ",
    busy: "ব্যস্ত",
    connect: "সংযুক্ত হন",
    viewProfile: "প্রোফাইল দেখুন",
    contactWeaver: "তাঁতির সাথে যোগাযোগ করুন",

    // Continue with other translations...
    welcomeWeaver: "স্বাগতম, মাস্টার তাঁতি!",
    empowerCraft: "AI সরঞ্জাম এবং সরকারি সহায়তা দিয়ে আপনার কারুশিল্পকে ক্ষমতায়ন করুন",
    budgetPlanner: "AI বাজেট পরিকল্পনাকারী",
    estimateBudget: "বাজেট অনুমান করুন",
    machinesRequired: "প্রয়োজনীয় মেশিন",
    numberOfLooms: "তাঁতের সংখ্যা",
    materialQuantity: "উপাদানের পরিমাণ (কেজি)",
    yarnQuantity: "সুতার পরিমাণ",
    laborDays: "শ্রম দিবস",
    workingDays: "কর্মদিবস",
    estimatedBudget: "আনুমানিক বাজেট",
    govSchemes: "সরকারি প্রকল্প",
    learningResources: "শিক্ষণ সম্পদ",
    profileManager: "প্রোফাইল ব্যবস্থাপক",
    uploadWork: "কাজের ছবি আপলোড করুন",
    accessCourses: "আপনার দক্ষতা বাড়ানোর জন্য কোর্স, গাইড এবং ভিডিও টিউটোরিয়াল অ্যাক্সেস করুন",
    uploadManage: "আপনার কাজ আপলোড করুন এবং আপনার বিশেষত্ব পরিচালনা করুন",

    // Government Schemes
    handloomScheme: "হ্যান্ডলুম তাঁতিদের ব্যাপক কল্যাণ প্রকল্প",
    handloomDesc: "হ্যান্ডলুম তাঁতিদের জন্য আর্থিক সহায়তা এবং বীমা কভারেজ",
    developmentScheme: "জাতীয় হ্যান্ডলুম উন্নয়ন কর্মসূচি",
    developmentDesc: "দক্ষতা উন্নয়ন এবং প্রযুক্তি আপগ্রেডেশন সহায়তা",
    yarnScheme: "সুতা সরবরাহ প্রকল্প",
    yarnDesc: "হ্যান্ডলুম তাঁতিদের জন্য ভর্তুকিযুক্ত সুতা সরবরাহ",
    learnMore: "আরও জানুন",

    // Resources
    traditionalTechniques: "ঐতিহ্যবাহী তাঁত কৌশল",
    digitalMarketing: "কারিগরদের জন্য ডিজিটাল মার্কেটিং",
    loomMaintenance: "তাঁত রক্ষণাবেক্ষণ ও যত্ন",
    course: "কোর্স",
    pdfGuide: "পিডিএফ গাইড",
    video: "ভিডিও",
    access: "অ্যাক্সেস",

    // Pagination
    previous: "আগের",
    next: "পরবর্তী",
    page: "পৃষ্ঠা",
    of: "এর",

    // Materials and Patterns
    cotton: "কটন",
    silk: "সিল্ক",
    khadi: "খাদি",
    linen: "লিনেন",
    chiffon: "শিফন",
    bandhani: "বান্দানি",
    kanjivaram: "কাঞ্জিভরম",
    ikat: "ইকাত",
    banarasi: "বেনারসি",
    geometric: "জ্যামিতিক",
    floral: "ফ্লোরাল",
    paisley: "পেইসলি",
    templeBorders: "মন্দির বর্ডার",
    zariWork: "জরির কাজ",
    blockPrint: "ব্লক প্রিন্ট",
    silkWeaving: "সিল্ক তাঁত",
    cottonSarees: "কটন শাড়ি",
    bananasiSaree: "বেনারসি শাড়ি",
  },
  ta: {
    // Navigation
    home: "முகப்பு",
    login: "உள்நுழைவு/பதிவு",
    userDashboard: "பயனர் டாஷ்போர்டு",
    weaverDashboard: "நெசவாளர் டாஷ்போர்டு",
    about: "பற்றி",
    contact: "தொடர்பு",
    tagline: "பாரம்பரியத்தை இதயங்களுடன் இணைத்தல்",

    // Common
    search: "தேடல்",
    filter: "வடிகட்டி",
    clear: "தெளிவுபடுத்து",
    apply: "விண்ணப்பிக்க",
    save: "சேமிக்க",
    cancel: "ரத்து செய்",
    edit: "திருத்து",
    delete: "நீக்கு",
    view: "காண்க",
    loading: "ஏற்றுகிறது...",
    noResults: "எந்த முடிவுகளும் இல்லை",

    // User Dashboard
    welcomeUser: "வரவேற்கிறோம், புடவை காதலர்!",
    discoverWeavers: "இந்தியாவில் உள்ள திறமையான பெண் நெசவாளர்களைக் கண்டுபிடித்து இணைந்திடுங்கள்",
    searchWeavers: "பெயர், பிராந்தியம் அல்லது சிறப்பு மூலம் நெசவாளர்களைத் தேடுங்கள்...",
    filterBy: "வடிகட்டு",
    pattern: "வடிவம்",
    material: "பொருள்",
    region: "பிராந்தியம்",
    allPatterns: "எல்லா வடிவங்கள்",
    allMaterials: "எல்லா பொருட்கள்",
    allRegions: "எல்லா பிராந்தியங்கள்",
    clearFilters: "வடிகட்டிகளை அழி",
    weaversFound: "நெசவாளர்கள் கண்டுபிடிக்கப்பட்டனர்",
    yearsExperience: "வருட அனுபவம்",
    specialties: "சிறப்புகள்",
    recentWork: "சமீபத்திய வேலை",
    languages: "மொழிகள்",
    priceRange: "விலை வரம்பு",
    reviews: "விமர்சனங்கள்",
    verified: "சரிபார்க்கப்பட்டது",
    available: "கிடைக்கும்",
    busy: "பிஸி",
    connect: "இணைக்க",
    viewProfile: "சுயவிவரத்தைக் காண்க",
    contactWeaver: "நெசவாளரைத் தொடர்பு கொள்ளவும்",

    // Weaver Dashboard
    welcomeWeaver: "வரவேற்கிறோம், மாஸ்டர் நெசவாளர்!",
    empowerCraft: "AI கருவிகள் மற்றும் அரசாங்க ஆதரவுடன் உங்கள் கைவினைக்கு அதிகாரம் அளியுங்கள்",
    budgetPlanner: "AI பட்ஜெட் திட்டமிடுபவர்",
    estimateBudget: "பட்ஜெட் மதிப்பீடு",
    machinesRequired: "தேவையான இயந்திரங்கள்",
    numberOfLooms: "தறிகளின் எண்ணிக்கை",
    materialQuantity: "பொருள் அளவு (கிலோ)",
    yarnQuantity: "நூல் அளவு",
    laborDays: "தொழிலாளர் நாட்கள்",
    workingDays: "வேலை நாட்கள்",
    estimatedBudget: "மதிப்பிடப்பட்ட பட்ஜெட்",
    govSchemes: "அரசு திட்டங்கள்",
    learningResources: "கற்றல் வளங்கள்",
    profileManager: "சுயவிவர மேலாளர்",
    uploadWork: "வேலை படங்களை பதிவேற்றவும்",
    accessCourses: "உங்கள் திறமைகளை மேம்படுத்த படிப்புகள், வழிகாட்டிகள் மற்றும் வீடியோ பயிற்சிக்கு அணுகவும்",
    uploadManage: "உங்கள் வேலையைப் பதிவேற்றி உங்கள் சிறப்புகளை நிர்வகிக்கவும்",

    // Government Schemes
    handloomScheme: "கைத்தறி நெசவாளர்களுக்கான விரிவான நலத்திட்ட திட்டம்",
    handloomDesc: "கைத்தறி நெசவாளர்களுக்கு நிதி உதவி மற்றும் காப்பீட்டு பாதுகாப்பு",
    developmentScheme: "தேசிய கைத்தறி மேம்பாட்டு திட்டம்",
    developmentDesc: "திறன் மேம்பாடு மற்றும் தொழில்நுட்ப மேம்பாட்டு ஆதரவு",
    yarnScheme: "நூல் வழங்கல் திட்டம்",
    yarnDesc: "கைத்தறி நெசவாளர்களுக்கு மானிய விலையில் நூல் வழங்கல்",
    learnMore: "மேலும் அறிக",

    // Resources
    traditionalTechniques: "பாரம்பரிய நெசவு நுட்பங்கள்",
    digitalMarketing: "கைவினைஞர்களுக்கான டிஜிட்டல் மார்க்கெட்டிங்",
    loomMaintenance: "தறி பராமரிப்பு மற்றும் பாதுகாப்பு",
    course: "பாடம்",
    pdfGuide: "PDF வழிகாட்டி",
    video: "வீடியோ",
    access: "அணுகல்",

    // Pagination
    previous: "முந்தைய",
    next: "அடுத்த",
    page: "பக்கம்",
    of: "இன்",

    // Materials and Patterns
    cotton: "பருத்தி",
    silk: "பட்டு",
    khadi: "காதி",
    linen: "லினன்",
    chiffon: "சிஃபான்",
    bandhani: "பந்தனி",
    kanjivaram: "காஞ்சிவரம்",
    ikat: "இக்கத்",
    banarasi: "பனாரசி",
    geometric: "வடிவியல்",
    floral: "பூக்கள்",
    paisley: "பைஸ்லி",
    templeBorders: "கோயில் எல்லைகள்",
    zariWork: "ஜரி வேலை",
    blockPrint: "பிளாக் பிரிண்ட்",
    silkWeaving: "பட்டு நெசவு",
    cottonSarees: "பருத்தி புடவைகள்",
    bananasiSaree: "பனாரசி புடவை",
  },
  te: {
    // Navigation
    home: "హోమ్",
    login: "లాగిన్/సైనప్",
    userDashboard: "యూజర్ డాష్‌బోర్డ్",
    weaverDashboard: "నేత కార్మిక డాష్‌బోర్డ్",
    about: "గురించి",
    contact: "సంప్రదింపులు",
    tagline: "వారసత్వాన్ని హృదయాలతో కలుపుట",

    // Common
    search: "వెతకండి",
    filter: "ఫిల్టర్",
    clear: "తొలగించు",
    apply: "వర్తించు",
    save: "సేవ్",
    cancel: "రద్దు చేయి",
    edit: "సవరించు",
    delete: "తొలగించు",
    view: "చూడండి",
    loading: "లోడ్ అవుతోంది...",
    noResults: "ఫలితాలు కనుగొనబడలేదు",

    // User Dashboard
    welcomeUser: "స్వాగతం, చీర ప్రేమికుడా!",
    discoverWeavers: "భారతదేశం అంతటా ఉన్న ప్రతిభావంతులైన మహిళా నేత కార్మికులను కనుగొని కనెక్ట్ అవ్వండి",
    searchWeavers: "పేరు, ప్రాంతం లేదా ప్రత్యేకత ద్వారా నేత కార్మికులను వెతకండి...",
    filterBy: "ఫిల్టర్ చేయండి",
    pattern: "నమూనా",
    material: "పదార్థం",
    region: "ప్రాంతం",
    allPatterns: "అన్ని నమూనాలు",
    allMaterials: "అన్ని పదార్థాలు",
    allRegions: "అన్ని ప్రాంతాలు",
    clearFilters: "ఫిల్టర్‌లను తొలగించండి",
    weaversFound: "నేత కార్మికులు కనుగొనబడ్డారు",
    yearsExperience: "సంవత్సరాల అనుభవం",
    specialties: "ప్రత్యేకతలు",
    recentWork: "సమీప పని",
    languages: "భాషలు",
    priceRange: "ధర పరిధి",
    reviews: "సమీక్షలు",
    verified: "ధృవీకరించబడింది",
    available: "అందుబాటులో ఉంది",
    busy: "బిజీ",
    connect: "కనెక్ట్",
    viewProfile: "ప్రొఫైల్‌ను చూడండి",
    contactWeaver: "నేత కార్మికుడిని సంప్రదించండి",

    // Weaver Dashboard
    welcomeWeaver: "స్వాగతం, మాస్టర్ నేత కార్మికుడా!",
    empowerCraft: "AI సాధనాలు మరియు ప్రభుత్వ మద్దతుతో మీ చేతివృత్తికి అధికారం ఇవ్వండి",
    budgetPlanner: "AI బడ్జెట్ ప్లానర్",
    estimateBudget: "బడ్జెట్ అంచనా",
    machinesRequired: "కావాల్సిన యంత్రాలు",
    numberOfLooms: "మగ్గాల సంఖ్య",
    materialQuantity: "పదార్థం పరిమాణం (కేజీ)",
    yarnQuantity: "నూలు పరిమాణం",
    laborDays: "శ్రమ దినాలు",
    workingDays: "పని దినాలు",
    estimatedBudget: "అంచనా బడ్జెట్",
    govSchemes: "ప్రభుత్వ పథకాలు",
    learningResources: "నేర్చుకునే వనరులు",
    profileManager: "ప్రొఫైల్ మేనేజర్",
    uploadWork: "పని చిత్రాలను అప్‌లోడ్ చేయండి",
    accessCourses: "మీ నైపుణ్యాలను మెరుగుపరచడానికి కోర్సులు, గైడ్‌లు మరియు వీడియో ట్యుటోరియల్‌లను యాక్సెస్ చేయండి",
    uploadManage: "మీ పనిని అప్‌లోడ్ చేయండి మరియు మీ ప్రత్యేకతలను నిర్వహించండి",

    // Government Schemes
    handloomScheme: "చేనేత కార్మికుల సమగ్ర సంక్షేమ పథకం",
    handloomDesc: "చేనేత కార్మికులకు ఆర్థిక సహాయం మరియు బీమా కవరేజ్",
    developmentScheme: "జాతీయ చేనేత అభివృద్ధి కార్యక్రమం",
    developmentDesc: "నైపుణ్యాభివృద్ధి మరియు సాంకేతిక నవీకరణ మద్దతు",
    yarnScheme: "నూలు సరఫరా పథకం",
    yarnDesc: "చేనేత కార్మికులకు సబ్సిడీతో కూడిన నూలు సరఫరా",
    learnMore: "మరింత తెలుసుకోండి",

    // Resources
    traditionalTechniques: "సాంప్రదాయ నేత పద్ధతులు",
    digitalMarketing: "హస్తకళాకారుల కోసం డిజిటల్ మార్కెటింగ్",
    loomMaintenance: "మగ్గం నిర్వహణ & సంరక్షణ",
    course: "కోర్సు",
    pdfGuide: "PDF గైడ్",
    video: "వీడియో",
    access: "సందర్శించండి",

    // Pagination
    previous: "మునుపటి",
    next: "తరువాత",
    page: "పేజీ",
    of: "యొక్క",

    // Materials and Patterns
    cotton: "పత్తి",
    silk: "పట్టు",
    khadi: "ఖద్దరు",
    linen: "నార",
    chiffon: "చిఫ్ఫోన్",
    bandhani: "బంధాని",
    kanjivaram: "కాஞ்சிవరం",
    ikat: "ఇక్కత్",
    banarasi: "బనారసి",
    geometric: "జ్యామితీయ",
    floral: "పూల",
    paisley: "పైస్లీ",
    templeBorders: "గుడి సరిహద్దులు",
    zariWork: "జరీ పని",
    blockPrint: "బ్లాక్ ప్రింట్",
    silkWeaving: "పట్టు నేత",
    cottonSarees: "కాటన్ చీరలు",
    bananasiSaree: "బనారసి చీర",
  },
  kn: {
    // Navigation
    home: "ಮುಖಪುಟ",
    login: "ಲಾಗಿನ್/ಸೈನಪ್",
    userDashboard: "ಬಳಕೆದಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    weaverDashboard: "ನೇಕಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    about: "ಬಗ್ಗೆ",
    contact: "ಸಂಪರ್ಕ",
    tagline: "ಪರಂಪರೆಯನ್ನು ಹೃದಯಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುವುದು",

    // Common
    search: "ಹುಡುಕಿ",
    filter: "ಫಿಲ್ಟರ್",
    clear: "ತೆರವುಗೊಳಿಸಿ",
    apply: "ಅನ್ವಯಿಸು",
    save: "ಉಳಿಸು",
    cancel: "ರದ್ದುಮಾಡು",
    edit: "ಸಂಪಾದಿಸು",
    delete: "ತೆಗೆದುಹಾಕು",
    view: "ವೀಕ್ಷಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    noResults: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ",

    // User Dashboard
    welcomeUser: "ಸ್ವಾಗತ, ಸೀರೆ ಪ್ರೇಮಿ!",
    discoverWeavers: "ಭಾರತದಾದ್ಯಂತ ಪ್ರತಿಭಾವಂತ ಮಹಿಳಾ ನೇಕಾರರನ್ನು ಅನ್ವೇಷಿಸಿ ಮತ್ತು ಸಂಪರ್ಕಿಸಿ",
    searchWeavers: "ಹೆಸರು, ಪ್ರದೇಶ ಅಥವಾ ವಿಶೇಷತೆಯಿಂದ ನೇಕಾರರನ್ನು ಹುಡುಕಿ...",
    filterBy: "ಫಿಲ್ಟರ್ ಮಾಡಿ",
    pattern: "ಮಾದರಿ",
    material: "ವಸ್ತು",
    region: "ಪ್ರದೇಶ",
    allPatterns: "ಎಲ್ಲಾ ಮಾದರಿಗಳು",
    allMaterials: "ಎಲ್ಲಾ ವಸ್ತುಗಳು",
    allRegions: "ಎಲ್ಲಾ ಪ್ರದೇಶಗಳು",
    clearFilters: "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ",
    weaversFound: "ನೇಕಾರರು ಕಂಡುಬಂದಿದ್ದಾರೆ",
    yearsExperience: "ವರ್ಷಗಳ ಅನುಭವ",
    specialties: "ವಿಶೇಷತೆಗಳು",
    recentWork: "ಇತ್ತೀಚಿನ ಕೆಲಸ",
    languages: "ಭಾಷೆಗಳು",
    priceRange: "ಬೆಲೆ ಶ್ರೇಣಿ",
    reviews: "ವಿಮರ್ಶೆಗಳು",
    verified: "ಧೃಢೀಕರಿಸಲಾಗಿದೆ",
    available: "ಲಭ್ಯವಿದೆ",
    busy: "ನಿರತ",
    connect: "ಸಂಪರ್ಕಿಸಿ",
    viewProfile: "ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ",
    contactWeaver: "ನೇಕಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ",

    // Weaver Dashboard
    welcomeWeaver: "ಸ್ವಾಗತ, ಮಾಸ್ಟರ್ ನೇಕಾರ!",
    empowerCraft: "AI ಪರಿಕರಗಳು ಮತ್ತು ಸರ್ಕಾರದ ಬೆಂಬಲದೊಂದಿಗೆ ನಿಮ್ಮ ಕರಕುಶಲತೆಗೆ ಅಧಿಕಾರ ನೀಡಿ",
    budgetPlanner: "AI ಬಜೆಟ್ ಯೋಜಕ",
    estimateBudget: "ಬಜೆಟ್ ಅಂದಾಜು",
    machinesRequired: "ಬೇಕಾದ ಯಂತ್ರಗಳು",
    numberOfLooms: "ಮಗ್ಗಗಳ ಸಂಖ್ಯೆ",
    materialQuantity: "ವಸ್ತು ಪ್ರಮಾಣ (ಕೆಜಿ)",
    yarnQuantity: "ನೂಲಿನ ಪ್ರಮಾಣ",
    laborDays: "ಕಾರ್ಮಿಕ ದಿನಗಳು",
    workingDays: "ಕೆಲಸದ ದಿನಗಳು",
    estimatedBudget: "ಅಂದಾಜು ಬಜೆಟ್",
    govSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    learningResources: "ಕಲಿಕೆಯ ಸಂಪನ್ಮೂಲಗಳು",
    profileManager: "ಪ್ರೊಫೈಲ್ ವ್ಯವಸ್ಥಾಪಕ",
    uploadWork: "ಕೆಲಸದ ಚಿತ್ರಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    accessCourses: "ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳನ್ನು ಹೆಚ್ಚಿಸಲು ಕೋರ್ಸ್‌ಗಳು, ಮಾರ್ಗದರ್ಶಿಗಳು ಮತ್ತು ವೀಡಿಯೊ ಟ್ಯುಟೋರಿಯಲ್‌ಗಳನ್ನು ಪ್ರವೇಶಿಸಿ",
    uploadManage: "ನಿಮ್ಮ ಕೆಲಸವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ವಿಶೇಷತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",

    // Government Schemes
    handloomScheme: "ಕೈಮಗ್ಗ ನೇಕಾರರ ಸಮಗ್ರ ಕಲ್ಯಾಣ ಯೋಜನೆ",
    handloomDesc: "ಕೈಮಗ್ಗ ನೇಕಾರರಿಗೆ ಆರ್ಥಿಕ ನೆರವು ಮತ್ತು ವಿಮಾ ರಕ್ಷಣೆ",
    developmentScheme: "ರಾಷ್ಟ್ರೀಯ ಕೈಮಗ್ಗ ಅಭಿವೃದ್ಧಿ ಕಾರ್ಯಕ್ರಮ",
    developmentDesc: "ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ಮೇಲ್ದರ್ಜೆಗೇರಿಸುವ ಬೆಂಬಲ",
    yarnScheme: "ನೂಲು ಸರಬರಾಜು ಯೋಜನೆ",
    yarnDesc: "ಕೈಮಗ್ಗ ನೇಕಾರರಿಗೆ ಸಬ್ಸಿಡಿ ದರದಲ್ಲಿ ನೂಲು ಸರಬರಾಜು",
    learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",

    // Resources
    traditionalTechniques: "ಸಾಂಪ್ರದಾಯಿಕ ನೇಯ್ಗೆ ತಂತ್ರಗಳು",
    digitalMarketing: "ಕುಶಲಕರ್ಮಿಗಳಿಗೆ ಡಿಜಿಟಲ್ ಮಾರ್ಕೆಟಿಂಗ್",
    loomMaintenance: "ಮಗ್ಗ ನಿರ್ವಹಣೆ ಮತ್ತು ಆರೈಕೆ",
    course: "ಕೋರ್ಸ್",
    pdfGuide: "ಪಿಡಿಎಫ್ ಮಾರ್ಗದರ್ಶಿ",
    video: "ವಿಡಿಯೋ",
    access: "ಪ್ರವೇಶ",

    // Pagination
    previous: "ಹಿಂದಿನ",
    next: "ಮುಂದೆ",
    page: "ಪುಟ",
    of: "ನ",

    // Materials and Patterns
    cotton: "ಹತ್ತಿ",
    silk: "ರೇಷ್ಮೆ",
    khadi: "ಖಾದಿ",
    linen: "ಲಿನಿನ್",
    chiffon: "ಚಿಫನ್",
    bandhani: "ಬಂಧನಿ",
    kanjivaram: "ಕಾಂಜೀವರಂ",
    ikat: "ಇಕಾತ್",
    banarasi: "ಬನಾರಸಿ",
    geometric: "ಜ್ಯಾಮಿತೀಯ",
    floral: "ಪುಷ್ಪ",
    paisley: "ಪೈಸ್ಲಿ",
    templeBorders: "ದೇವಾಲಯದ ಗಡಿಗಳು",
    zariWork: "ಜರಿ ಕೆಲಸ",
    blockPrint: "ಬ್ಲಾಕ್ ಪ್ರಿಂಟ್",
    silkWeaving: "ರೇಷ್ಮೆ ನೇಯ್ಗೆ",
    cottonSarees: "ಹತ್ತಿ ಸೀರೆಗಳು",
    bananasiSaree: "ಬನಾರಸಿ ಸೀರೆ",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState("en")

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
